# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'timesTwo
#'
#'Multiply a number by two
#'
#'@param x input value
#'
#'@return x times two
#'
#'@examples
#'timesTwo(3)
#'
#' @export
timesTwo <- function(x) {
    .Call(`_mypackage_3_timesTwo`, x)
}

